### ISSUE TITLE
Setup questions

### ISSUE THREAD

**Issue by chrisguida** [ElementsProject/filebazaar#7]
I've got `filebazaar` installed and running, like so:

```
$ filebazaar
FileBazaar serving /home/bitcoin/ForSale on port 9678, browse at http://0.0.0.0:9678/
```

...but when I visit it in my browser, I get a text-only display (rather than a pretty interface as in the readme), and the links don't work. I suppose I have something misconfigured?

`_filebazaar.yaml` looks like:

```
---

### Server settings

env: production

#port: 9678
host: 0.0.0.0
#url: http://my-url.com

### Lightning Charge

charge_url: http://localhost:9112
charge_token: SECRET

### FileBazaar settings

# The directory containing the files for sale
# defaults to the directory containing this file
# directory: /path/to/files

# The default file price, can be overridden for individual files (see below)
#default_price: 0.25 USD

# Expiry times
#invoice_ttl: 3600 # lock-in exchange rate for 1 hour
#download_ttl: 172800 # make download available for 2 days after payment

# Secret for generating HMAC access tokens (required)
token_secret: SECRET

# Directory to keep cached preview files
# defaults to `{directory}/_filebazaar_cache`
#cache_path: /path/to/filebazaar_cache

### Looks & feel

# See available themes on https://bootswatch.com
#theme: yeti

# Add custom CSS
#css: |
#  body { background: blue }
#  a { color: orange }

# Set custom views directory
#views_dir: /path/to/custom/views

# Set custom static files directory
#static_dir: /path/to/custom/static

### Files settings

files:
  Books/:
    Mastering-Bitcoin.pdf:
      price: 5 USD
      button: Buy this book

```

Thanks for your help :)
